//! # fuzz — Fuzz Testing Infrastructure
//!
//! Defines the fuzz target registry, harness configuration, and corpus
//! management types used by infinityOS fuzz testing.  Actual fuzzing is
//! performed by external harnesses (e.g., `cargo-fuzz` / `libFuzzer`); this
//! module provides the shared data structures and metadata they reference.
//!
//! Fuzz targets live under `runtime-rust/fuzz/fuzz_targets/` (generated by
//! `cargo fuzz init`).  This module keeps the registry of known targets and
//! their seed corpus configuration so that CI and quality reporting widgets
//! can reason about coverage and history without depending on the fuzzer
//! binary itself.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use thiserror::Error;

// ---------------------------------------------------------------------------
// Error
// ---------------------------------------------------------------------------

/// Errors from the fuzz module.
#[derive(Debug, Error)]
pub enum FuzzError {
    /// A target with the given name already exists.
    #[error("duplicate fuzz target: {0}")]
    DuplicateTarget(String),
    /// A referenced target does not exist.
    #[error("unknown fuzz target: {0}")]
    UnknownTarget(String),
    /// A corpus entry contains invalid base64 data.
    #[error("invalid base64 data in corpus entry '{0}': {1}")]
    InvalidCorpusData(String, String),
}

// ---------------------------------------------------------------------------
// Parser / serializer categories
// ---------------------------------------------------------------------------

/// Categories of parsers/serializers that benefit most from fuzzing.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FuzzCategory {
    /// JSON and binary serialization/deserialization.
    Serialization,
    /// Node-graph wire format parsing.
    GraphParsing,
    /// Mesh artifact framing/deframing.
    MeshProtocol,
    /// ActionLog event parsing.
    ActionLogParsing,
    /// FFI boundary data validation.
    FfiBoundary,
    /// Input validation at layer boundaries.
    InputValidation,
}

// ---------------------------------------------------------------------------
// Corpus entry
// ---------------------------------------------------------------------------

/// A seed corpus entry: a named, base64-encoded input blob.
///
/// Seed entries are checked in under `runtime-rust/fuzz/corpus/<target>/`
/// and used to bootstrap the fuzzer with interesting starting points.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CorpusEntry {
    /// Entry name (filename in the corpus directory).
    pub name: String,
    /// Base64-encoded raw bytes.
    pub data_b64: String,
    /// Optional comment describing what property this input exercises.
    pub description: Option<String>,
}

impl CorpusEntry {
    /// Create a new seed corpus entry from raw bytes.
    pub fn from_bytes(name: impl Into<String>, bytes: &[u8]) -> Self {
        // simple base64 encoding without external dep
        let data_b64 = Base64Standard::encode(bytes);
        Self { name: name.into(), data_b64, description: None }
    }

    /// Attach a description.
    pub fn with_description(mut self, desc: impl Into<String>) -> Self {
        self.description = Some(desc.into());
        self
    }

    /// Decode and return the raw bytes.
    ///
    /// # Errors
    /// Returns [`FuzzError::InvalidCorpusData`] if the stored base64 contains
    /// characters outside the standard alphabet.
    pub fn bytes(&self) -> Result<Vec<u8>, FuzzError> {
        Base64Standard::decode(&self.data_b64)
            .map_err(|msg| FuzzError::InvalidCorpusData(self.name.clone(), msg))
    }
}

// Minimal base64 encoder/decoder (standard alphabet, no padding required for
// this use-case since we round-trip through our own codec).
struct Base64Standard;

impl Base64Standard {
    const ALPHABET: &'static [u8; 64] =
        b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

    fn encode(input: &[u8]) -> String {
        let mut encoded = String::with_capacity(input.len().div_ceil(3) * 4);
        for chunk in input.chunks(3) {
            let b0 = chunk[0];
            let b1 = if chunk.len() > 1 { chunk[1] } else { 0 };
            let b2 = if chunk.len() > 2 { chunk[2] } else { 0 };
            encoded.push(Self::ALPHABET[(b0 >> 2) as usize] as char);
            encoded.push(Self::ALPHABET[((b0 & 3) << 4 | b1 >> 4) as usize] as char);
            encoded.push(if chunk.len() > 1 {
                Self::ALPHABET[((b1 & 0xf) << 2 | b2 >> 6) as usize] as char
            } else {
                '='
            });
            encoded.push(if chunk.len() > 2 {
                Self::ALPHABET[(b2 & 0x3f) as usize] as char
            } else {
                '='
            });
        }
        encoded
    }

    fn decode(input: &str) -> Result<Vec<u8>, String> {
        // Build a lookup table: 0xFF marks invalid characters.
        let table: [u8; 256] = {
            let mut t = [0xFFu8; 256];
            for (i, &c) in Self::ALPHABET.iter().enumerate() {
                t[c as usize] = i as u8;
            }
            t['=' as usize] = 0; // padding is treated as zero
            t
        };
        let input = input.trim_end_matches('=');
        let mut decoded = Vec::with_capacity(input.len() * 3 / 4);
        let chars: Vec<u8> = input.bytes().collect();
        for chunk in chars.chunks(4) {
            for &byte in chunk {
                if table[byte as usize] == 0xFF {
                    return Err(format!("invalid base64 character: {:?}", byte as char));
                }
            }
            let c0 = table[chunk[0] as usize];
            let c1 = if chunk.len() > 1 { table[chunk[1] as usize] } else { 0 };
            let c2 = if chunk.len() > 2 { table[chunk[2] as usize] } else { 0 };
            let c3 = if chunk.len() > 3 { table[chunk[3] as usize] } else { 0 };
            decoded.push((c0 << 2) | (c1 >> 4));
            if chunk.len() > 2 { decoded.push((c1 << 4) | (c2 >> 2)); }
            if chunk.len() > 3 { decoded.push((c2 << 6) | c3); }
        }
        Ok(decoded)
    }
}

// ---------------------------------------------------------------------------
// Fuzz target
// ---------------------------------------------------------------------------

/// A registered fuzz target.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FuzzTarget {
    /// Unique target name (matches the file under `fuzz/fuzz_targets/`).
    pub name: String,
    /// Category of parser/serializer being fuzzed.
    pub category: FuzzCategory,
    /// Human-readable description.
    pub description: String,
    /// Seed corpus entries for this target.
    pub seed_corpus: Vec<CorpusEntry>,
    /// Maximum allowed input length passed to the fuzzer (bytes).
    pub max_input_len: usize,
    /// Whether CI runs this target (some targets may be manual-only).
    pub ci_enabled: bool,
}

impl FuzzTarget {
    /// Create a new fuzz target.
    pub fn new(
        name: impl Into<String>,
        category: FuzzCategory,
        description: impl Into<String>,
    ) -> Self {
        Self {
            name: name.into(),
            category,
            description: description.into(),
            seed_corpus: vec![],
            max_input_len: 4096,
            ci_enabled: true,
        }
    }

    /// Add a seed corpus entry.
    pub fn with_seed(mut self, entry: CorpusEntry) -> Self {
        self.seed_corpus.push(entry);
        self
    }

    /// Override the maximum input length.
    pub fn with_max_len(mut self, len: usize) -> Self {
        self.max_input_len = len;
        self
    }
}

// ---------------------------------------------------------------------------
// Fuzz target registry
// ---------------------------------------------------------------------------

/// Registry of all known fuzz targets.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct FuzzRegistry {
    targets: HashMap<String, FuzzTarget>,
}

impl FuzzRegistry {
    /// Build the canonical infinityOS fuzz target registry.
    pub fn canonical() -> Self {
        let mut reg = Self::default();

        let _ = reg.register(
            FuzzTarget::new(
                "fuzz_json_deserializer",
                FuzzCategory::Serialization,
                "Fuzz the serde_json deserializer on arbitrary byte sequences to detect panics or invalid output",
            )
            .with_seed(
                CorpusEntry::from_bytes("empty_object", b"{}")
                    .with_description("minimal valid JSON object"),
            )
            .with_seed(
                CorpusEntry::from_bytes("empty_array", b"[]")
                    .with_description("minimal valid JSON array"),
            ),
        );

        let _ = reg.register(
            FuzzTarget::new(
                "fuzz_graph_wire_format",
                FuzzCategory::GraphParsing,
                "Fuzz the node-graph wire-format parser with arbitrary bytes",
            )
            .with_seed(
                CorpusEntry::from_bytes(
                    "minimal_graph",
                    br#"{"nodes":[],"edges":[]}"#,
                )
                .with_description("empty graph JSON"),
            ),
        );

        let _ = reg.register(
            FuzzTarget::new(
                "fuzz_mesh_framing",
                FuzzCategory::MeshProtocol,
                "Fuzz the mesh artifact framing/deframing layer",
            )
            .with_max_len(65536),
        );

        let _ = reg.register(
            FuzzTarget::new(
                "fuzz_actionlog_event",
                FuzzCategory::ActionLogParsing,
                "Fuzz ActionLog event deserialization to find malformed-input crashes",
            ),
        );

        let _ = reg.register(
            FuzzTarget::new(
                "fuzz_ffi_boundary",
                FuzzCategory::FfiBoundary,
                "Fuzz C↔Rust FFI boundary input validation routines",
            )
            .with_max_len(256),
        );

        let _ = reg.register(
            FuzzTarget::new(
                "fuzz_input_validator",
                FuzzCategory::InputValidation,
                "Fuzz the ify-security InputValidator with arbitrary JSON payloads",
            ),
        );

        reg
    }

    /// Register a target.
    ///
    /// # Errors
    /// Returns [`FuzzError::DuplicateTarget`] if a target with the same name exists.
    pub fn register(&mut self, target: FuzzTarget) -> Result<(), FuzzError> {
        if self.targets.contains_key(&target.name) {
            return Err(FuzzError::DuplicateTarget(target.name));
        }
        self.targets.insert(target.name.clone(), target);
        Ok(())
    }

    /// Look up a target by name.
    pub fn get(&self, name: &str) -> Option<&FuzzTarget> {
        self.targets.get(name)
    }

    /// Return all registered targets.
    pub fn all(&self) -> impl Iterator<Item = &FuzzTarget> {
        self.targets.values()
    }

    /// Return targets enabled for CI.
    pub fn ci_targets(&self) -> impl Iterator<Item = &FuzzTarget> {
        self.targets.values().filter(|t| t.ci_enabled)
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn canonical_registry_has_expected_targets() {
        let reg = FuzzRegistry::canonical();
        assert!(reg.get("fuzz_json_deserializer").is_some());
        assert!(reg.get("fuzz_graph_wire_format").is_some());
        assert!(reg.get("fuzz_mesh_framing").is_some());
        assert!(reg.get("fuzz_actionlog_event").is_some());
        assert!(reg.get("fuzz_ffi_boundary").is_some());
        assert!(reg.get("fuzz_input_validator").is_some());
    }

    #[test]
    fn duplicate_registration_is_rejected() {
        let mut reg = FuzzRegistry::default();
        let t = FuzzTarget::new("target", FuzzCategory::Serialization, "desc");
        reg.register(t.clone()).unwrap();
        assert!(reg.register(t).is_err());
    }

    #[test]
    fn corpus_entry_roundtrips_bytes() {
        let original = b"hello fuzz world";
        let entry = CorpusEntry::from_bytes("test", original);
        assert_eq!(entry.bytes().unwrap(), original);
    }

    #[test]
    fn corpus_entry_bytes_errors_on_invalid_base64() {
        let mut entry = CorpusEntry::from_bytes("test", b"hello");
        // Corrupt the stored base64 with an invalid character.
        entry.data_b64 = "!!!invalid!!!".to_string();
        assert!(entry.bytes().is_err());
    }

    #[test]
    fn ci_targets_subset_of_all() {
        let reg = FuzzRegistry::canonical();
        let ci_count = reg.ci_targets().count();
        let all_count: usize = reg.all().count();
        assert!(ci_count <= all_count);
    }
}
